POST /residents/7/relationship HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "familySerialNumber": 2,
  "familyRelationshipCode": "부"
}

###

PUT /residents/7/relationship/2 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "familyRelationshipCode": "모"
}

###

DELETE /residents/7/relationship/4
Host: localhost:8080